Add package.json
ARMmbed/mbed-js-easy-connect pull request #1
Opened 2016-12-02 03:23 UTC by janjongboom

@thegecko

2016-12-02 05:35 UTC, janjongboom commented
OK. Tested against latest JerryScript. Can now connect to the internet.

2016-12-02 15:33 UTC, thegecko requested changes
Are there odd spaces/tabs in there?

2016-12-03 01:45 UTC, janjongboom commented
@thegecko This is the only library that used 2-space indentation for C++, changed it to 4 spaces.

2016-12-03 13:48 UTC, thegecko approved these changes

2016-12-04 07:04 UTC, merged